name: CI/CD - TrackPlacement Release
on:
  push:
    tags: ['v*']

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create Release Archive
        run: |
          zip -r TrackPlacement.mcpack . -x "*.git*" -x "./.github/*" -x "./README.md" -x "./.gitignore"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: TrackPlacement.mcpack

      - name: Upload to CurseForge
        continue-on-error: true
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: "1483473"
          game_endpoint: "minecraft-bedrock"
          file_path: "TrackPlacement.mcpack"
          display_name: "TrackPlacement ${{ github.ref_name }}"
          release_type: "release"
          game_versions: "1.21,26.0,26.3"
