name: CI/CD - TrackPlacement Release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Version Number (e.g., 1.21.0)'
        required: false
      changelog_override:
        description: 'Manual Changelog (Optional)'
        required: false

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release Archives
        run: |
          zip -r TrackPlacement.mcpack . -x "*.git*" -x "./.github/*" -x "./README.md" -x "./.gitignore"
          cp TrackPlacement.mcpack TrackPlacement.zip

      - name: Upload to Modrinth
        if: github.event_name == 'release' || github.event.inputs.version_override != ''
        continue-on-error: true
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: "lDi9Keu1"
          files: "TrackPlacement.zip"
          version: "${{ github.event.inputs.version_override || github.event.release.tag_name }}"
          changelog: "${{ github.event.inputs.changelog_override || github.event.release.body }}"
          loaders: '["minecraft"]'
          game-versions: '["1.21"]'

      - name: Upload to CurseForge
        if: github.event_name == 'release' || github.event.inputs.version_override != ''
        continue-on-error: true
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: "1483473"
          game_endpoint: "minecraft-bedrock"
          file_path: "TrackPlacement.mcpack"
          display_name: "TrackPlacement ${{ github.event.inputs.version_override || github.event.release.tag_name }}"
          release_type: "release"
          game_versions: "1.21"
